config/routes.rb
Pruebajose::Application.routes.draw do
  get 'static_pages/index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner navbar-newsoft">
        <div class="container">
          <%= link_to "Newsoft", '#', id: "logo" %>
          <nav>
            <ul class="nav pull-right main-nav-newsoft">
              

              <li class="<%= 'selected' if current_page?(static_pages_index_path) %>" ><%= link_to "Inicio", '#' %></li>

              
                <!--<div class="dropdown">-->
                  <a href="#" class="dropdown-toggle", data-toggle="dropdown">Productos</a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <li>Recursos humanos</li>
                    <li>Finanzas</li>
                    <li>Construcci&oacute;n</li>
                    <li>Manufactura</li>
                    <li>Otras aplicaciones</li>
                  </ul>
                <!--</div>-->
              </li>
              <li><%= link_to "Partners", '#' %></li>
              <li><%= link_to "Clientes", '#' %></li>
              <li><%= link_to "Soporte", '#' %></li>
              <li><%= link_to "Mejoras", '#' %></li>
              <li><%= link_to "Contacto", '#' %></li>
              <li><%= link_to "Preguntas Frecuentes", '#' %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/index.html.erb

<% provide :title, 'Newsoft - Inicio' %>
<div class="center hero-unit">
  <h1>NEWSOFT</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", '#', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>